source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!


target 'DropDemo' do
    
    pod 'XLPagerTabStrip', '~> 7.0'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SDWebImage/GIF', '>= 0'
end

